### ISSUE TITLE
Multi-domain support

### ISSUE THREAD

**Issue by thomasgenster** [em-group/firefly-iii#1]
The site should be able to handle multiple domains.

This means that 
- users should have an extra column in the DB which states which users belongs to which sites.
- all info related to the site (domain-wise) should be in a .env file
    - a suggestion is to load domain-specific .env files based on the hostname in bootstrap/app.php (.budget-planner.com.env)
- template and/or styling should be set in the .env file
- "splash" pages for each domain
    - upon entering budget-planner.com, a splash page is rendered, showing contact information, about us, terms, prices etc. (this will be designed later, NOT a priority in the beginning)

**Comment by nipemgroup** [comment]
I propose the solution created in 71ca38bcc95739edb4efa8fdd62bb733d776f335, for overloading the environment variables. In initial testing, it seems to work well, and fail gracefully.
One thing to note, that may be a dealbreaker, is that when overwriting the environment variables dynamically, on a per-request basis, we'll be unable to cache the config, as any of the sub environments has the option of overwriting any of the configurations. This alone, makes me want to consider another path, unless we can somehow separate each environment's config, and cache them individually.
It may make more sense to move to a key-value store, for domain-specific overwrites.

**Comment by thomasgenster** [comment]
Looks like a good solution.
I don't think we can expect so much traffic that it makes any impact on performance caching the config, but then again, I am not quite sure how much difference not caching the config makes for this system. Unless there are other sides to caching the config besides performance that's important?
