### ISSUE TITLE
All WhitelabelConfig values are null

### ISSUE THREAD

**Issue by thomasgenster** [em-group/firefly-iii#15]
It seems all values put into whitelabel_configs in the DB are being set to null on the model. It registers the DB config entries fine, but I am not getting the correct value.

DB:
![Screenshot 2019-09-19 at 12 02 57](https://user-images.githubusercontent.com/1425786/65234744-7528ad00-dad5-11e9-932a-12adf246647e.png)

Dump of `config('whitelabel')` array:
![Screenshot 2019-09-19 at 12 03 29](https://user-images.githubusercontent.com/1425786/65234783-8671b980-dad5-11e9-818c-39db9cbf96e5.png)

**Comment by nipemgroup** [comment]
Can't replicate, when are you dumping the config? (Not that it should matter, what's posted should be working correctly, when the id is also being set automatically).

Are you editing the values in the db, or in the backend? As a note, any additional properties we're supposed to be specifying for whitelabels, should be added to the default list in https://github.com/em-group/firefly-iii/blob/develop/config/whitelabels.php#L4-L8, so they're automatically populated in the backend whitelabel management.

**Comment by thomasgenster** [comment]
Yap, worked when I added the them to the default_configs and changed the value from the backend. I just added them to the DB which explains it.

**Comment by nipemgroup** [comment]
Ah yes, I see what the issue was now - The values you'd added weren't json encoded, so the decoding failed :shipit:
