### ISSUE TITLE
Rename of App Name

### ISSUE THREAD

**Issue by thomasgenster** [em-group/firefly-iii#3]
A lot of places, Firefly is hardcoded into JS files and views. This needs to be replaced with the APP_NAME from the .env file that is loaded.

**Comment by nipemgroup** [comment]
Additionally, help pages also display the app name - But they're dynamically loaded from the original github page. Whether it's necessary to fork that repo too, and redirect the calls, do a dynamic swap of the app name, or simply just leave it all as-is, should probably be discussed further.

https://github.com/em-group/firefly-iii/blob/master/app/Helpers/Help/Help.php#L77-L103

**Comment by thomasgenster** [comment]
Ideally we should fork the help repo too and change the name, but I think it would be easier to just dynamically change the name.
