### ISSUE TITLE
Add a "change membership type" page

### ISSUE THREAD

**Issue by thomasgenster** [em-group/firefly-iii#37]
Currently there are no ways for users to change their current membership plan.

We need a button next to the "Cancel membership" button (or somewhere else) where the user can change which membership-plan their account will be renewed into upon next renewal.
Changing this should not change the level of the current membership. But if they are currently on a Premium membership, they can choose to be renewed into a Basic membership which will happen upon renewal.

**Comment by nipemgroup** [comment]
> Changing this should not change the level of the current membership.

But if they want to upgrade from basic to premium, shouldn't they get upgraded as quickly as possible? They'll likely be upgrading to use some of the premium features, presumably, so it doesn't make sense to have them wait until the next renewal.
Practically, we could split the difference in cost, and just do a transaction for that, or withdraw the full amount, and maybe add the 30 days to whatever they have left of the current membershp (essentially giving them a discount for the extra days), if we want to be fair, and possibly give an extra incentive to upgrade.

**Comment by thomasgenster** [comment]
> But if they want to upgrade from basic to premium, shouldn't they get upgraded as quickly as possible?
That is correct. Not sure what the best solution is - it makes sense to charge only 50% of the renewal price if there is 15 days left of the membership, but would that not require a rework of the "membership-flow" since we'd be altering the current membership, and not do a renewal per se?
