### ISSUE TITLE
Unsubscribe button

### ISSUE THREAD

**Issue by thomasgenster** [em-group/firefly-iii#78]
We need to implement the same Unsubscribe function in this as we have for the other non-budget sites.

If possible, make a page that looks like the Log In page, and show the email field along with the text from the other sites. Once we have an URL for this page, I will figure out where to add it on the various pages (footer/header).

**Comment by nipemgroup** [comment]
![image](https://user-images.githubusercontent.com/5850936/97188412-c361b280-17a3-11eb-8cc0-35be94688a07.png)

Added on `/unsub` (can of course be changed in `/routes/web.php`).

**Comment by thomasgenster** [comment]
Can we add the text from the other sites? 

> If you want to cancel your membership with AtzPhoto.com, please type in the email you used to sign up.
If you do not remember the email you signed up with, you can contact our support department at SUPPRT@SUPPORT.COM who will be happy to assist you.

Perhaps also change the text on the button :D

**Comment by thomasgenster** [comment]
I will add some more text and fix the button when I add the links in the templates

**Comment by nipemgroup** [comment]
> Perhaps also change the text on the button :D

Don't be unreasonable now
